"""
SereniTeach Crisis Alert System
Sends email notifications to front desk when behavioral crises are detected
"""
import os
import logging
from datetime import datetime
from flask_mail import Mail, Message
from flask import current_app

logger = logging.getLogger(__name__)

class CrisisAlertSystem:
    """Handles crisis detection and automated alert notifications"""
    
    def __init__(self):
        self.front_desk_email = "stevenrayhinojosa@gmail.com"
        logger.info("Crisis alert system initialized for email notifications")
    
    def is_crisis_situation(self, analysis_data):
        """
        Determine if the situation qualifies as a crisis requiring immediate alert
        
        Parameters:
        - analysis_data: Dictionary containing behavior analysis results
        
        Returns:
        - Boolean indicating if this is a crisis situation
        """
        if not analysis_data:
            return False
        
        # Check for emergency signals
        if analysis_data.get('is_emergency', False):
            return True
        
        # Check for high-risk keywords
        keywords = analysis_data.get('keywords', [])
        crisis_keywords = [
            'weapon', 'dangerous', 'violent', 'threatening', 'harm', 'hurt', 
            'emergency', 'crisis', 'safety', 'injured', 'attack', 'fight'
        ]
        
        if any(keyword in crisis_keywords for keyword in keywords):
            return True
        
        # Check severity level if available
        severity = analysis_data.get('severity', '')
        if severity and severity.lower() in ['high', 'severe', 'critical']:
            return True
        
        # Check protocol analysis for emergency indicators
        protocol_analysis = analysis_data.get('protocol_analysis', {})
        if protocol_analysis.get('is_emergency', False):
            return True
        
        return False
    
    def generate_crisis_message(self, analysis_data, location="classroom"):
        """
        Generate appropriate crisis alert message for email
        
        Parameters:
        - analysis_data: Dictionary containing behavior analysis results
        - location: Physical location of the incident
        
        Returns:
        - Tuple containing (subject, body) for email
        """
        timestamp = datetime.now().strftime("%I:%M %p on %B %d, %Y")
        
        # Extract key information
        keywords = analysis_data.get('keywords', [])
        behavior_type = analysis_data.get('behavior_type', 'behavioral incident')
        
        # Create email subject
        subject = f"URGENT: Behavioral Crisis Alert - {location.title()}"
        
        # Create detailed email body
        body = f"BEHAVIORAL CRISIS ALERT\n"
        body += f"Time: {timestamp}\n"
        body += f"Location: {location.title()}\n"
        body += f"Situation: {behavior_type.title()}\n\n"
        
        if keywords:
            key_indicators = ', '.join(keywords[:5])  # Show top 5 keywords
            body += f"Key Indicators: {key_indicators}\n\n"
        
        body += "IMMEDIATE RESPONSE REQUIRED\n\n"
        body += "This alert was automatically generated by the SereniTeach behavioral decision support system. "
        body += "Please respond to this situation as soon as possible.\n\n"
        body += "Generated by SereniTeach Crisis Alert System"
        
        return subject, body
    
    def send_crisis_alert(self, analysis_data, location="classroom"):
        """
        Send email alert to front desk about crisis situation
        
        Parameters:
        - analysis_data: Dictionary containing behavior analysis results
        - location: Physical location of the incident
        
        Returns:
        - Dictionary with success status and message details
        """
        try:
            # Generate the alert message
            subject, body = self.generate_crisis_message(analysis_data, location)
            
            # Check if email credentials are configured
            mail_username = current_app.config.get('MAIL_USERNAME')
            mail_password = current_app.config.get('MAIL_PASSWORD')
            
            if not mail_username or not mail_password:
                # Demonstration mode - log the email that would be sent
                logger.warning("Email credentials not configured - running in demonstration mode")
                logger.info(f"DEMO EMAIL ALERT:\nTo: {self.front_desk_email}\nSubject: {subject}\nBody: {body}")
                
                return {
                    "success": True,
                    "message": f"Crisis alert logged (demo mode) - would send to {self.front_desk_email}",
                    "email": self.front_desk_email,
                    "subject": subject,
                    "alert_text": body,
                    "demo_mode": True
                }
            
            # Create email message
            msg = Message(
                subject=subject,
                sender=current_app.config.get('MAIL_DEFAULT_SENDER', mail_username),
                recipients=[self.front_desk_email],
                body=body
            )
            
            # Send email using Flask-Mail
            mail = current_app.extensions.get('mail')
            if mail:
                mail.send(msg)
                logger.info(f"Crisis alert email sent successfully to {self.front_desk_email}")
                
                return {
                    "success": True,
                    "message": "Crisis alert email sent to front desk",
                    "email": self.front_desk_email,
                    "subject": subject,
                    "alert_text": body
                }
            else:
                logger.error("Mail service not configured")
                return {
                    "success": False,
                    "error": "Email service not configured",
                    "message": "Flask-Mail not initialized"
                }
            
        except Exception as e:
            logger.error(f"Failed to send crisis alert email: {str(e)}")
            
            # If email fails, still log the alert for demonstration
            subject, body = self.generate_crisis_message(analysis_data, location)
            logger.warning(f"Email failed, logging alert: To: {self.front_desk_email}, Subject: {subject}")
            
            return {
                "success": True,
                "message": f"Crisis alert logged (email failed) - attempted to send to {self.front_desk_email}",
                "email": self.front_desk_email,
                "subject": subject,
                "alert_text": body,
                "email_failed": True,
                "error_details": str(e)
            }
    
    def process_behavior_incident(self, analysis_data, location="classroom"):
        """
        Process a behavior incident and send alert if crisis detected
        
        Parameters:
        - analysis_data: Dictionary containing behavior analysis results
        - location: Physical location of the incident
        
        Returns:
        - Dictionary with processing results and alert status
        """
        # Check if this qualifies as a crisis
        is_crisis = self.is_crisis_situation(analysis_data)
        
        if is_crisis:
            logger.warning("Crisis situation detected - sending alert")
            alert_result = self.send_crisis_alert(analysis_data, location)
            
            return {
                "crisis_detected": True,
                "alert_sent": alert_result["success"],
                "alert_details": alert_result
            }
        else:
            logger.info("Behavior incident logged - no crisis alert needed")
            return {
                "crisis_detected": False,
                "alert_sent": False,
                "alert_details": {"message": "No crisis detected"}
            }

# Create global instance
crisis_alert_system = CrisisAlertSystem()